### ISSUE TITLE
objects not showing up

### ISSUE THREAD

**Issue by fabian0hofmann** [tegami-lpr/xplane_importer#1]
I installed it like any other addon (from the zip file) and tried to import a .obj file but nothing showed up. 

I'm using Blender 2.92.

Any troubleshooting ideas?

**Comment by tegami-lpr** [comment]
First of all try to import your obj using Blender 2.83. Not sure if the plugin will work under 2.9* versions.

**Comment by fabian0hofmann** [comment]
I uninstalled 2.92 and installed 2.83 LTS. Still does not work unfortunately. Can I send you any kind of log file?

**Comment by tegami-lpr** [comment]
You are welcome. And, if it possible, please attach object file.
